[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
security_token_program = "9qfVMGUqZubCJWmCXP4HomRRpkq6fWgcn6XZp4Z3gj4i"

[programs.devnet]
security_token_program = "9qfVMGUqZubCJWmCXP4HomRRpkq6fWgcn6XZp4Z3gj4i"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-node tests/test.ts"
